name: 'Get Submodule'
description: 'Downloads and builds a git submodule'
inputs:
  definitions:
    description: 'CMake definitions'
    required: true
    default: ''
  input_var:
    description: 'CMake definitions'
    required: true
    default: ''
outputs:
  output_var:
    description: "CMake definitions output"
    value: ${{ steps.clone.outputs.output_var }}
runs:
  using: "composite"
  steps: 
    - name: Clone
      shell: bash
      id: clone
      run: |
        # newDefinitions=${{ inputs.definitions }}${{ inputs.input_var }}
        # echo "::set-output name=output_var::$newDefinitions"
        newDefinitions="${{ env.TEST_SUB_SUB_ENV }}${{ inputs.input_var }}"
        newDefinitions+="test -DDEPENDENCY_GEOMETRIC_TOOLS_INCLUDE=/d/a/util_image/util_image/third_party_libs/GeometricTools/GTE"
        echo "TEST_SUB_SUB_ENV=$(echo $newDefinitions)" >> $GITHUB_ENV
        
        echo "hello world"  >> cmake_vars.txt   
        cat cmake_vars.txt     
        echo "hello siva" >> cmake_vars.txt   
        cat cmake_vars.txt
        
        #$(echo $tmpDef)"

